- name: Update Apt cache
  apt:
    update_cache: yes
    
- name: Install Aptitude
  package:
    name: aptitude
    state: present
    
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
